# Generated by Django 5.2.10 on 2026-02-19 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True)),
                ('lon', models.FloatField(blank=True)),
                ('appeared_at', models.DateTimeField()),
                ('disappeared_at', models.DateTimeField()),
                ('level', models.IntegerField(blank=True)),
                ('health', models.IntegerField(blank=True)),
                ('strength', models.IntegerField(blank=True)),
                ('defence', models.IntegerField(blank=True)),
                ('evo', models.ForeignKey(default='self', on_delete=django.db.models.deletion.CASCADE, related_name='ddgh', to='pokemon_entities.pokemon')),
                ('pokemon', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, related_name='dfg', to='pokemon_entities.pokemon')),
            ],
        ),
    ]
