# Generated by Django 5.2.10 on 2026-02-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0014_alter_pokemon_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='description',
            field=models.CharField(blank=True, default=' ', max_length=500, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title_en',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='Название по английски'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title_jp',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='НАзвание по японски'),
            preserve_default=False,
        ),
    ]
